# fly.toml app configuration file generated for nwmanager on 2024-11-11T04:32:38-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nwmanager'
primary_region = 'iad'

[build]
[build.args]
GO_VERSION = '1.22.5'

[http_service]
processes = ["app"]
internal_port = 8080
auto_start_machines = true
min_machines_running = 1
force_https = false

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
